//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamCheddarSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assigned_Idea
    {
        public Assigned_Idea()
        {
            this.Append_Log = new HashSet<Append_Log>();
        }
    
        public int Ambassador_id { get; set; }
        public int School_id { get; set; }
        public int Idea_num { get; set; }
        public string Status { get; set; }
        public int Assigned_id { get; set; }
        public Nullable<System.DateTime> Completion_date { get; set; }
    
        public virtual School School { get; set; }
        public virtual ICollection<Append_Log> Append_Log { get; set; }
        public virtual Idea Idea { get; set; }
        public virtual User User { get; set; }
    }
}
