//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamCheddarSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public Code()
        {
            this.Users = new HashSet<User>();
            this.Event_Log = new HashSet<Event_Log>();
        }
    
        public int Code_id { get; set; }
        public string Code_def { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Event_Log> Event_Log { get; set; }
    }
}
