//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamCheddarSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int File_id { get; set; }
        public string File_name { get; set; }
        public byte[] File_data { get; set; }
        public int Idea_num { get; set; }
    
        public virtual Idea Idea { get; set; }
    }
}
