//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamCheddarSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idea
    {
        public Idea()
        {
            this.Files = new HashSet<File>();
            this.Assigned_Idea = new HashSet<Assigned_Idea>();
        }
    
        public int Idea_num { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_submitted { get; set; }
        public Nullable<System.DateTime> Comp_date { get; set; }
        public int User_id { get; set; }
        public string Title { get; set; }
        public bool Assigned { get; set; }
        public string Justification { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<Assigned_Idea> Assigned_Idea { get; set; }
    }
}
