//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamCheddarSharp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamCheddarSharpEntities : DbContext
    {
        public TeamCheddarSharpEntities()
            : base("name=TeamCheddarSharpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Code> Codes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Archive> Archives { get; set; }
        public virtual DbSet<Idea> Ideas { get; set; }
        public virtual DbSet<Assigned_Idea> Assigned_Idea { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Append_Log> Append_Log { get; set; }
        public virtual DbSet<Event_Log> Event_Log { get; set; }
    }
}
