//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamCheddarSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Ideas = new HashSet<Idea>();
            this.Append_Log = new HashSet<Append_Log>();
            this.Assigned_Idea = new HashSet<Assigned_Idea>();
            this.Event_Log = new HashSet<Event_Log>();
        }
    
        public int User_id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public int Role { get; set; }
        public string PasswordSalt { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual ICollection<Idea> Ideas { get; set; }
        public virtual ICollection<Append_Log> Append_Log { get; set; }
        public virtual ICollection<Assigned_Idea> Assigned_Idea { get; set; }
        public virtual ICollection<Event_Log> Event_Log { get; set; }
    }
}
